In [20]:
from numpy import random

x = random.uniform(-1000,1001,size=(1000, 3))
y = random.randint(2,size=(1000, 1))

for i in range(0,1000):
  y_i = (500*x[i][0])-(413*x[i][1])+(17*x[i][2])+203
  if y_i >= 0:
    y[i] = 1
  else:
    y[i] = -1

print(x[:10])
print(y[:10])

[[ 166.22019987  370.46786094  546.64566887]
 [-110.67990166 -333.98630132  712.1687734 ]
 [-284.60563557 -168.36284066 -298.07249905]
 [-609.29828656  658.58283681  996.99285191]
 [  72.24121784   77.43774816 -413.19770113]
 [-643.81646329 -875.76275616  391.60114608]
 [-128.49330255  482.18113156   35.63427489]
 [ 621.84766894  -45.41723305 -339.8919505 ]
 [-443.83993766 -242.68865904  613.59455619]
 [ 594.05217756 -420.43172147  893.13480925]]
[[-1]
 [ 1]
 [-1]
 [-1]
 [-1]
 [ 1]
 [-1]
 [ 1]
 [-1]
 [ 1]]


In [21]:
w1=0
w2=0
w3=0
w4=0

'''
1. while loop will run untill it converge the minimum error
2. for loop will be run 1000 (as dataset size) and each time it find the value mismatch it will update the weights
3. if predicted value from weights and the actual value sign mismatch (value*y[i]), the weigths will be update formula (w = w + y_actual*x_i)
4. it iterate 1000 times >>> each time find any mismatch that will update the weights >>> for loop closes >>> flag becomes False (flag=False) >>> run again for mimatch
5. As the 1000 iteration will be done and no mismatch find that means there is no error... So no need to update the weights
6. Then flag = True and by this the while close
'''

while (True):
    for i in range(1000):
      flag= True
      y_predict = w1*x[i][0] + w2*x[i][1] + w3*x[i][2] + w4
      if y_predict*y[i] <=0:
        flag=False
        w1 += y[i] * x[i][0]
        w2 += y[i] * x[i][1]
        w3 += y[i] * x[i][2]
        w4 += y[i] * 1
        break
      else:
        continue
    if flag==True:
      print(w1,w2,w3,w4)
      break

[7657.92938541] [-6326.15888832] [240.17512582] [-129]


In [22]:
print(w1[0]/500)
print(w2[0]/-413)
print(w3[0]/17)
print(w4[0])

15.31585877082361
15.317576000772357
14.12794857784356
-129
